language: julia

os:
  - linux

julia:
  - 1.0

notifications:
  email: sunbergzach@gmail.com

after_success:
  - julia -e 'if VERSION >= v"0.7.0-" using Pkg end; cd(Pkg.dir("Example")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
